name: 'codegen'
author: djshuckerow@google.com
description: 'Generates class metadata'

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_value: any
  cereal: 
    path: packages/cereal
  meta: any

dev_dependencies:
  # build_runner: any
  # built_value_generator: any
  cereal_generator:
    path: packages/cereal_generator
  build_runner: ^1.0.0
