name: cereal_generator
author: djshuckerow@google.com
description: A serializer library for dart with no-overhead code generation.
homepage: https://github.com/DaveShuckerow/cereal

version: 0.0.1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.0.0
