name: cereal_example
author: djshuckerow@google.com
description: Example of the cereal Dart serializer.
homepage: https://github.com/DaveShuckerow/cereal

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  cereal: 
    path: ../
  meta: ^1.1.0

dev_dependencies:
  cereal_generator: ^0.0.1
  build_runner: ^1.0.0

dependency_overrides:
  cereal_generator:
    path: ../../cereal_generator